[package]
name = "kujibiki2"
version = "0.1.0"
authors = ["pco2699 <aenkun@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
